services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - path: ./.env.compose
        required: true
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:8.0.9
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    environment:
      MONGODB_DATABASE: "crm"
    healthcheck:
      test: mongosh --quiet --eval "try{rs.status().ok}catch(e){rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}).ok}" | grep -q 1
      interval: 5s
      retries: 10
    command: [ "--replSet", "rs0", "--bind_ip_all" ]

  redis:
    image: redis:8.0.3
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db:

